"""Tools package - imports all tool modules to register their endpoints."""

# Import all tool modules to trigger endpoint registration
from . import (
    amass,
    arjun,
    dalfox,
    dirb,
    dirsearch,
    dnsenum,
    feroxbuster,
    ffuf,
    fierce,
    gau,
    gobuster,
    hakrawler,
    httpx,
    jaeles,
    katana,
    masscan,
    nikto,
    nmap,
    nmap_advanced,
    nuclei,
    paramspider,
    rustscan,
    sqlmap,
    subfinder,
    wafw00f,
    waybackurls,
    wfuzz,
    wpscan,
    x8,
)
